use 5.008008;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME              => 'Args::Simple',
    VERSION_FROM      => 'lib/Args/Simple.pm', # finds $VERSION
    PREREQ_PM         => {}, # e.g., Module::Name => 1.1
    ($] >= 5.005 ?     ## Add these new keywords supported since 5.005
      (ABSTRACT_FROM  => 'lib/Args/Simple.pm', # retrieve abstract from module
       AUTHOR         => 'mobrien <mobrien@x-ray.at>') : ()),
);
